/*
 * Copyright (C) 2017 iData Inc. - All Rights Reserved
 * Developed by William Zhang
 */

#ifndef ID_OPCUA_DB_DEF_H
#define ID_OPCUA_DB_DEF_H

#define ID_OPCUA_DATABASE_NAMESPACE_ID              1
#define ID_OPCUA_DATABASE_VIEW                      1001
#define ID_OPCUA_DATABASE_OBJECT                    1002

/* 11xx - Unicode (Wide Functions) */

#define ID_OPCUA_DATABASE_UNICODE_SQLCONNECT        1101
#define ID_OPCUA_DATABASE_UNICODE_SQLSETCOMMIT      1102
#define ID_OPCUA_DATABASE_UNICODE_SQLCOMMIT         1103
#define ID_OPCUA_DATABASE_UNICODE_SQLDISCONNECT     1104
#define ID_OPCUA_DATABASE_UNICODE_SQLALLOCHANDLE    1105
#define ID_OPCUA_DATABASE_UNICODE_SQLCLOSE          1106
#define ID_OPCUA_DATABASE_UNICODE_SQLRESETPARAMS    1107
#define ID_OPCUA_DATABASE_UNICODE_SQLFREEHANDLE     1108

#define ID_OPCUA_DATABASE_UNICODE_SQLEXECDIRECT     1109
#define ID_OPCUA_DATABASE_UNICODE_SQLSELECT         1110
#define ID_OPCUA_DATABASE_UNICODE_SQLINSERT         1111
#define ID_OPCUA_DATABASE_UNICODE_SQLUPDATE         1112
#define ID_OPCUA_DATABASE_UNICODE_SQLDELETE         1113
#define ID_OPCUA_DATABASE_UNICODE_SQLFETCH          1114
#define ID_OPCUA_DATABASE_UNICODE_SQLPREPARE        1115
#define ID_OPCUA_DATABASE_UNICODE_SQLBIND           1116
#define ID_OPCUA_DATABASE_UNICODE_SQLEXECUTE        1117

/* 12xx - ANSI/UTF8 Functions (Multibyte Functions) */

#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLCONNECT      1201
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLSETCOMMIT    1202
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLCOMMIT       1203
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLDISCONNECT   1204
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLALLOCHANDLE  1205
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLCLOSE        1206
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLRESETPARAMS  1207
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLFREEHANDLE   1208

#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLEXECDIRECT   1209
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLSELECT       1210
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLINSERT       1211
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLUPDATE       1212
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLDELETE       1213
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLFETCH        1214
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLPREPARE      1215
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLBIND         1216
#define ID_OPCUA_DATABASE_ANSI_UTF8_SQLEXECUTE      1217

#endif